class_name Sound_Component

extends Node3D

@onready var ak_sounds = [$"../ARMS_CAM_POS/ak_aim_pos/ARMS/ak-74_arms/sounds/shoot_sound", $"../ARMS_CAM_POS/ak_aim_pos/ARMS/ak-74_arms/sounds/reload_sound"]
@onready var pistol_sounds = [$"../ARMS_CAM_POS/pistol_cam_pos/pistol_aim_pos/pistol_arms/Sketchfab_model/3ab9f780f2294ec8ba398c31f25c6b54_fbx/Object_2/RootNode/Armature/sound/shoot", $"../ARMS_CAM_POS/pistol_cam_pos/pistol_aim_pos/pistol_arms/Sketchfab_model/3ab9f780f2294ec8ba398c31f25c6b54_fbx/Object_2/RootNode/Armature/sound/reload", $"../ARMS_CAM_POS/pistol_cam_pos/pistol_aim_pos/pistol_arms/Sketchfab_model/3ab9f780f2294ec8ba398c31f25c6b54_fbx/Object_2/RootNode/Armature/sound/mag1", $"../ARMS_CAM_POS/pistol_cam_pos/pistol_aim_pos/pistol_arms/Sketchfab_model/3ab9f780f2294ec8ba398c31f25c6b54_fbx/Object_2/RootNode/Armature/sound/mag2"]
@onready var geyger_sounds = [$"../ARMS_CAM_POS/geyger_cam_pos/geiger_arms/Sketchfab_model/810f0276179d4425a118b331d5f38189_fbx/Object_2/RootNode/Rig/Object_8/Skeleton3D/BoneAttachment3D/sounds/middle", $"../ARMS_CAM_POS/geyger_cam_pos/geiger_arms/Sketchfab_model/810f0276179d4425a118b331d5f38189_fbx/Object_2/RootNode/Rig/Object_8/Skeleton3D/BoneAttachment3D/sounds/low", $"../ARMS_CAM_POS/geyger_cam_pos/geiger_arms/Sketchfab_model/810f0276179d4425a118b331d5f38189_fbx/Object_2/RootNode/Rig/Object_8/Skeleton3D/BoneAttachment3D/sounds/high", $"../ARMS_CAM_POS/geyger_cam_pos/geiger_arms/Sketchfab_model/810f0276179d4425a118b331d5f38189_fbx/Object_2/RootNode/Rig/Object_8/Skeleton3D/BoneAttachment3D/sounds/not_have"]
@onready var sniper_sounds = [$"../ARMS_CAM_POS/sniper_cam_pos/sniper_aim_position/sniper_samopal_arms/shoot_sound", $"../ARMS_CAM_POS/sniper_cam_pos/sniper_aim_position/sniper_samopal_arms/zatvor_sound", $"../ARMS_CAM_POS/sniper_cam_pos/sniper_aim_position/sniper_samopal_arms/magaz_out", $"../ARMS_CAM_POS/sniper_cam_pos/sniper_aim_position/sniper_samopal_arms/magaz_up", $"../ARMS_CAM_POS/sniper_cam_pos/sniper_aim_position/sniper_samopal_arms/zatvor_out", $"../ARMS_CAM_POS/sniper_cam_pos/sniper_aim_position/sniper_samopal_arms/zatvor_up"]
@onready var say_sounds = [$"../sounds/voice_sound/pisk"]
